blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

### Generic Veiw (class-based view)
urlpatterns=[
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/chart/', views.result_chart, name='chart'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.template import loader

from .models import Question, Choice

from django.http import Http404

# Create your views here.

### Generic View (class-based views)

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    """Return the last five published questions."""
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# def index(request):
#     # return HttpResponse("hello")
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#
#     # output=', '.join([q.question_text for q in latest_question_list])
#     # return HttpResponse(output)
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context,request))
#
# def detail(request, question_id):
#     # return HttpResponse("You're looking at question %s" %question_id)
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request,'polls/detail.html',{'question':question})

# def results(request, question_id):
#     # response = HttpResponse("You're looking at the results of question %s" %question_id)
#     # return response
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request, 'polls/results.html', {'question':question})
#
def vote(request, question_id):
    # return HttpResponse("You're voting on question %s" %question_id)
    question = get_object_or_404(Question, pk=question_id)

    for id_check in request.POST.getlist('choice'):
        try:
            selected_choice = question.choice_set.get(pk=id_check)
        except(KeyError,Choice.DoesNotExist):
            #Redisplay the question voting form
            return render(request, 'polls/detail.html', {
                'question':question,
                'error_message':"You're didn't select a choice",
            })
        else:
            selected_choice.votes+=1
            selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

def make_chart_data(data_question):

    my_data = list()
    for choice in data_question.choice_set.all():
        my_dict = dict()
        my_dict['name'] = choice.choice_text
        my_dict['y'] = choice.votes
        my_data.append(my_dict)

    chart_data = [{
        'name': 'Votes',
        'colorByPoint': 'true',
        'data': my_data,
    }]

    return chart_data

import json

def result_chart(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    chart_data = make_chart_data(question)
    dump = json.dumps(chart_data)

    chart_title = {
        'text': '투표결과 <br>' + question.question_text
    }

    dump_title = json.dumps(chart_title)

    return render(request, 'polls/chart.html', {'chart_data': dump, 'chart_title': dump_title})

polls/templates/polls/chart.html
{% extends 'base.html' %}
{% block title %} Polls {% endblock %}

{% block content %}
    <div id="container" style="margin-top: 20px;"></div>

    {% load static %}
    <script type="text/javascript"> var chart_data = {{chart_data|safe}} </script>
    <script type="text/javascript"> var chart_title = {{chart_title|safe}} </script>
    <script src="https://code.highcharts.com/highcharts.js"></script>

    <script defer src = "{% static 'polls/javascript.js' %}"></script>
{% endblock%}

<!--
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://code.highcharts.com/highcharts.js"></script>
</head>
<body>
    <div id="container" style="margin-top: 20px;"></div>

    {% load static %}
    <script type="text/javascript"> var chart_data = {{chart_data|safe}} </script>
    <script type="text/javascript"> var chart_title = {{chart_title|safe}} </script>

    <script defer src = "{% static 'polls/javascript.js' %}"></script>
</body>
</html>
-->

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block title %} Polls {% endblock %}

{% block content %}
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

    <h1>{{question.question_text}}</h1>
    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="POST">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="checkbox" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
        <input type="submit" value="vote">
    </form>
    <!--<ul>-->
    <!--    {% for choice in question.choice_set.all %}-->
    <!--    <li>{{choice.choice_text}}</li>-->
    <!--    {% endfor %}-->
    <!--</ul>-->
    <!--{{question}}-->
    <br>
    <a href="{% url 'polls:index' %}">Back to Questions</a>

{% endblock%}

polls/templates/polls/index.html
{% extends 'base.html' %}
{% block title %} Polls {% endblock %}

{% block content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Question</th>
        </tr>
    </thead>
    <tbody>
        {% for bookmark in object_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                    {% if latest_question_list %}
                <ul>
                    <td>
                        {% for question in latest_question_list %}
                                <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
                        {% endfor %}
                    </td>
                </ul>
                    {% else %}
                        <p>No polls are available.</p>
                    {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock%}

<!--
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>
-->

polls/templates/polls/results.html
{% extends 'base.html' %}
{% block title %} Polls {% endblock %}

{% block content %}
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

    <h1>{{question.question_text}}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.vote|pluralize}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    <a href="{% url 'polls:chart' question.id %}">Chart</a>
    <br>
    <a href="{% url 'polls:index' %}">Back to Questions</a>
{% endblock%}